### ISSUE TITLE
Solver does not implement signal handling

### ISSUE THREAD

**Issue by daajoe** [timhae/sudokusat-example#2]
Your solver does not implement signal handling to the started process tree. This results in the situation that the sat solver (clasp) might still be running even though the benchmark tool or cluster scheduler sent a kill signal to the solver after timeout.
(check with kill -15 mysolver or kill -9 mysolver)

```
import signal
# SETUP SIGNAL HANDLING
signal.signal(signal.SIGTERM, utils.signals.handler)
signal.signal(signal.SIGINT, utils.signals.handler)

#!/usr/bin/env python
# coding=utf-8
import logging
import os
import sys

import psutil

def handler(signum, frame):
    logging.error('signum %s' % signum)
    current_process = psutil.Process()
    children = current_process.children(recursive=True)
    for child in children:
        logging.error('Child pid is {}\n'.format(child.pid))
        logging.error('Killing child.')
        try:
            os.kill(child.pid, 15)
        except OSError as e:
            logging.warn('Process might already be gone. See error below.')
            logging.warn('%s' % str(e))

    logging.warn('SIGNAL received')
    if signum == 15:
        raise TimeoutException('signal')
    else:
        raise InterruptException('signal')


def nothing(signum, frame):
    logging.warn('SIGNAL received\n')
    logging.warn('SIGNAL ignored...\n')
```

might be helpful

**Comment by timhae** [comment]
please verify that this was fixed and reopen if you still have issues

**Comment by daajoe** [comment]
Does not work properly.

(reprobench) $ ./solver.py ../../foo.py ../../instances/private/private.cnf
---
  501 14651  7114   0  5:16PM ttys001    0:01.40 python3 ./solver.py ../../foo.py ../../instances/private/25/table5-1.normal.txt
  501 14652 14651   0  5:16PM ttys001    0:06.61 python ../../foo.py private.cnf
$ kill -15 14651
---
results in
Terminated: 15
--- 
but solver will continue running.

Example code for the foo.py
```
#!/usr/bin/env python

while True:
    print('foobar')
```

**Comment by timhae** [comment]
I seem unable to reproduce that issue.. I modified `foo.py` a little, here is my testing program:

```
#!/usr/bin/env python3

import time
import signal
import sys

def handler(num, stack):
    print('recieved signal', num)
    sys.exit(0)

signal.signal(signal.SIGTERM, handler)
signal.signal(signal.SIGINT, handler)

while True:
    print('running')
    time.sleep(1)
```

now when I issue `python3 solver.py ./foo.py ../instances/table9-1.txt` this runs in the background and as soon as I press `ctrl+c` or `kill -15` the program stops running, as well as the `foo.py`. I can verify this by checking the `table9-1.sol` file which contains a few lines `running` and then `recieved signal 15` or `recieved signal 2` and `recieved signal 15` which is what I expect. And I also expect the solver to exit on recieving those signal, which it does as far as I can tell. Can you provide further instructions on how to reproduce the issue?

**Comment by daajoe** [comment]
On which platform are you running your solver?

**Comment by daajoe** [comment]
You should not rely on the correct behavior of the subsolver as the subsolver might get stuck.
In your source code you run:

```
    def handler(self, _num, _frame):
        self.process.terminate()
```

This has two issues. 
First you might run into a NPE, if the process has not yet been startet.
Second it disallows you to start scripts that to not properly care about the process hierarchy as well as that it relies on the situation that the subsolver properly terminates. If you expect so then you should at least wait for the termination and check not just send a signal and quit. However, if you don't like to care Popen.kill() would be the right command, which indeed is the same if you use Windows (due the way how it is implemented).

**Comment by timhae** [comment]
I am running on linux, but I will just replace the calls with `.kill()` then. Does the solver still run in the background or is it being terminated?
