### ISSUE TITLE
Provide only one Solver per branch

### ISSUE THREAD

**Issue by daajoe** [timhae/sudokusat-example#3]
Make sure that your master contains only one solver and it is clear how to invoke the solver from reprobench.

**Comment by timhae** [comment]
I modified the `benchmark.yml` adding two more teams, that seemed like a reasonable approach since then I can compare results of the two solvers. Since they are identical at the moment this does not make a lot of sense though..

```
+  team2:
+    module: python_naive.MySudokuSolver
+    parameters:
+      clasp:
+        solver: clasp
+  team3:
+    module: python_improved.MySudokuSolver
+    parameters:
+      clasp:
+        solver: clasp
```

**Comment by daajoe** [comment]
This was not a recommendation, but a request. I will not test a solver that contains more than one configuration in the master branch. Make up your mind, which solver you want to have tested. If you add an additional solver in another branch that's your thing.

Thanks.

**Comment by timhae** [comment]
daf5fbe removed all additional solvers, I put them in a separate branch
